apiVersion: v1
kind: Pod
metadata:
  name: populare-db-proxy
  labels:
    app: populare
spec:
  containers:
  - image: kostaleonard/populare_db_proxy:0.0.2
    name: populare-db-proxy
    ports:
    - containerPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: populare-db-proxy
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: populare
