apiVersion: apps/v1
kind: Deployment
metadata:
  name: populare
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: populare
  template:
    metadata:
      name: populare
      labels:
        app: populare
    spec:
      containers:
        - image: kostaleonard/populare-offline:1.0.7 # TODO turn online
          name: populare
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /version.json
              port: 80
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /version.json
              port: 80
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: populare
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: populare
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: populare-db-proxy
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: populare-db-proxy
  template:
    metadata:
      name: populare-db-proxy
      labels:
        app: populare-db-proxy
    spec:
      containers:
      - image: kostaleonard/populare_db_proxy:0.0.8
        name: populare-db-proxy
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - name: db-certs
          mountPath: /etc/populare-db-proxy/db-certs/
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
      volumes:
      - name: db-certs
        secret:
          secretName: db-certs
---
apiVersion: v1
kind: Service
metadata:
  name: populare-db-proxy
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: populare-db-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      name: reverse-proxy
      labels:
        app: reverse-proxy
    spec:
      containers:
        - image: kostaleonard/populare-reverse-proxy:0.0.2
          name: reverse-proxy
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: reverse-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-client
  template:
    metadata:
      name: mock-client
      labels:
        app: mock-client
    spec:
      containers:
        - image: yauritux/busybox-curl
          name: mock-client
          args:
            - sleep
            - "1000000"
          readinessProbe:
            exec:
              command:
                - echo
                - ok
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - echo
                - ok
            periodSeconds: 5
            initialDelaySeconds: 15
