apiVersion: v1
kind: Pod
metadata:
  name: populare-db-proxy
  labels:
    app: populare
spec:
  containers:
  - image: kostaleonard/populare-db-proxy:0.0.2
    name: populare-db-proxy
    ports:
    - containerPort: 8000
      protocol: TCP
