apiVersion: apps/v1
kind: Deployment
metadata:
  name: populare-db-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: populare-db-proxy
  template:
    metadata:
      name: populare-db-proxy
      labels:
        app: populare-db-proxy
    spec:
      containers:
      - image: kostaleonard/populare_db_proxy:0.0.2
        name: populare-db-proxy
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: populare-db-proxy
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: populare-db-proxy
