- name: Check docker service status
  ansible.builtin.service:
    name: docker
    state: started

- name: Check wireguard container status
  # We could also use docker_container_info, but that requires Python 3.6 for
  # f-strings (and other dependencies, like cryptography) in the docker
  # package. But since we just want to make sure the wireguard server is
  # running, we can do docker ps. grep will exit with non-zero status if
  # linuxserver/wireguard is not running.
  ansible.builtin.shell: set -o pipefail && docker ps | grep linuxserver/wireguard
  become: true
  changed_when: false
