name: Deploy infrastructure
on: [push, pull_request]
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Lint and validate EKS plan
        run: |
          cd eks-tf
          terraform init
          terraform fmt -check
          terraform plan
      - name: Lint and validate Kubernetes plan
        run: |
          cd kubernetes-tf
          terraform init
          terraform fmt -check
          terraform validate
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "ansible/"
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
    # TODO
  #deploy-infrastructure:
    # TODO
  #deploy-kubernetes:
    # TODO
  #destroy-kubernetes:
    # TODO
  #destroy-infrastructure:
    # TODO
