name: Destroy infrastructure
on: [workflow_dispatch]
jobs:
  destroy-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Destroy Kubernetes infrastructure
        run: |
          cd kubernetes-tf
          terraform init
          terraform destroy -auto-approve
  destroy-infrastructure:
    runs-on: ubuntu-latest
    needs: [destroy-kubernetes]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Destroy terraform infrastructure
        run: |
          cd eks-tf
          terraform init
          terraform destroy -auto-approve
